config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/show' => 'hello#show'
  get 'hello/link' => 'hello#link'
  get 'hello/log' => 'hello#log'
  get 'hello/post' => 'hello#post'
  get 'hello/my' => 'hello#my'
  get 'hello/article1' => 'hello#article1'
  get 'hello/link_en' => 'hello#link_en'
  get 'hello/log_en' => 'hello#log_en'
  get 'hello/log_en' => 'hello#log_en'
  get 'hello/post_en' => 'hello#post_en'
  get 'hello/my_en' => 'hello#my_en'

  

  get 'hello/:tag_id' => 'hello#spring', as: 'hello_spring'
  root 'hello#index'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags, dependent: :destroy
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_many :tweet_tags, dependent: :destroy
    has_many :tags, through: :tweet_tags
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。
         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 }
         mount_uploader :image, ImageUploader
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         has_many :comments, dependent: :destroy
         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    @comment = tweet.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    
    def link
    end
    def link_en
    end
    def log
    end
    def log_en
    end
    def post
    end
    def post_en
    end
    def my
    end
    def my_en
    end
    def article1
    end
    def index
        

        
        if params[:search] == nil
        @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
        elsif params[:search] == ''
        @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
        else
        #部分検索
        @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%').order(created_at: "DESC").page(params[:page]).per(3)
        end
        
    
    end

    def show
    end

    def spring
        @tags = Tag.where(name: '春')
        @number = params[:tag_id].to_i

        @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all

    end

    def summer
    end

    def autumn
    end

    def winter
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(tweet_id: params[:tweet_id])
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/tweets_controller.rb
    class TweetsController < ApplicationController
    
        before_action :authenticate_user!
        
        def index
          if params[:search] == nil
          @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
          elsif params[:search] == ''
          @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
          else
          #部分検索
          @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%').order(created_at: "DESC").page(params[:page]).per(3)
          end
          @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
          @q = Tweet.ransack(params[:q])
          @tweets = @q.result(distinct: true)
          
        end
  
        
  
      def new
          @tweet = Tweet.new
          
      end
  
      def create
          @tweet = Tweet.new(tweet_params)
          @tweet.user_id = current_user.id
          if @tweet.save
            redirect_to :action => "index"
          else
            redirect_to :action => "new"
          end
         
      end
  
      def show
        @tweet = Tweet.find(params[:id])
        @like = Like.new
        
      end
  
      def edit
        @tweet = Tweet.find(params[:id])
       
      end
        
      def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)
          redirect_to :action => "show", :id => @tweet.id
        else
          redirect_to :action => "new"
        end
      end
  
      def destroy
        Tweet.find(params[:id]).destroy
       redirect_to action: :index
      end
      
     
  
      private
      def tweet_params
          params.require(:tweet).permit(:user_id, :body, :title, :material, :image, tag_ids: [])  
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def show
      @user = User.find(params[:id]) 
      if params[:search] == nil
        @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
        elsif params[:search] == ''
        @tweets= Tweet.all.order(created_at: "DESC").page(params[:page]).per(6)
        else
        #部分検索
        @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%').order(created_at: "DESC").page(params[:page]).per(3)
        end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb


<div class="top_image-container">
  <%= image_tag('top-image.jpg', :size => '2000x800') %>
    <div class="sub-container">
      <p>Vase</p>
    </div>
    <div class="top-container">
      <%= link_to "ログインはこちら", tweets_path ,class: 'btn btn-info' %>
      <%= link_to "新規登録はこちら", new_user_registration_path ,class: 'btn btn-info' %>
    </div>
</div>

<div class="scroll">
<div class="cp_arrows">
  <h2>Scroll</h2>
  <div class="cp_arrow cp_arrowfirst"></div>
  <div class="cp_arrow cp_arrowsecond"></div>
</div>
</div>



<div class="fixed-bg bg01">
<div class="fixed-bg-content">
  <h2>About Vase</h2>
</div>

</div>

<div class="scroll-bg bg-color01">
<div id="scroll-bg-content">
  <p>Vaseとは誰でも気軽にお花に関する情報を共有できるサイトです。
  <br>
  はじめは難しいと感じるかもしれませんが、飾り方、管理の仕方などコメントで聞いてみましょう。
  <br>
  ほかの人の作品も参考になるかもしれません。
  <br>
  当サイト管理人おすすめのお花や飾り方、作品も紹介しているのでぜひご覧ください！
  <br>
  </p>
  <%= link_to "About more", hello_link_path , :controller => "hello", :action => "link" ,class: 'btn btn-info' %>
  
</div>
</div>

<div class="fixed-bg bg02">
<div class="fixed-bg-content">
  <h2>Article</h2>
</div>
</div>

<div class="scroll-bg bg-color02">
<div id="scroll-bg-content">
  <p>コチラでは定期的に更新されている記事を読むことができます。
  <br>
  季節のおすすめのお花、いいねの多かった作品の紹介などをしています。
  <br>
  
  </p>
  <%= link_to "記事はコチラ", hello_show_path , :controller => "hello", :action => "show" ,class: 'btn btn-info' %>
</div>
</div>

<div class="fixed-bg bg03">
<div class="fixed-bg-content">
  <h2>Seasonal Flower</h2>
</div>
</div>

<div class="scroll-bg bg-color03">
<div id="scroll-bg-content">
  <p>コチラのページでは、それぞれの季節ごとの作品を見ることができます。
  </p>
  <div class="season-container">
  <div class="spring-box">
    <%= link_to image_tag('spring1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 1), method: :get %>
    <div class="spring-title">Spring</div>
    </div>
  <div class="summer-box">
    <%= link_to image_tag('summer1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 2), method: :get %>
    <div class="spring-title">Summer</div>
    </div>
  <div class="autumn-box">
    <%= link_to image_tag('autumn1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 3), method: :get  %>
    <div class="spring-title">Autumn</div>
    </div>
  <div class="winter-box">
  <%= link_to image_tag('winter1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 4), method: :get  %>
  <div class="spring-title">Winter</div>
  </div>
</div>
  </div>
  
</div>

<div class="fixed-bg bg04">
<div class="fixed-bg-content">
  <h2>Collection</h2>
</div>
</div>


<div class="scroll-bg-content">
 
  <div class="scroll-bg bg-color04">
    <div id="page-box">
      <%= page_entries_info @tweets %>
    </div>
  
    <% @tweets.each do |t| %>
  
      <div class="tweet">
      
          <div class="tweet-user-name-box">
          <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
          </div>
          <div class="tweet-image-box">
            <% if t.image.present? %>
            <%= link_to tweet_path(t.id) do %>
              <%= image_tag t.image_url, size: '400x300'  %>
            <% end %>
            <% else %>
            <%= link_to tweet_path(t.id) do %>
              <img src="/images/default.jpg" width="400px" height="300px">
            <% end %>
            <% end %> 
            <figcaption>
            <div class="tweet-title-box">
            <% if t.title.present? %>
            <%= t.title %>
            <% else %>
            <a>タイトルなし</a>
            <% end %>
            </div>
            <div class="tweet-info-item">
            ✿<%= t.liked_users.count %>
            <%= link_to "詳細へ", tweet_path(t.id) ,class: 'btn btn-outline-danger'%>
            
          </div>
          </figcaption>

          
            
            
          </div>
          
          
      </div>
     
    <% end %>
    
</div>
</div>
<hr class="cp_hr07" />
<div id="page-box">
<%= paginate @tweets %>
</div>


<%= javascript_pack_tag 'tweets/index' %>







app/views/hello/link.html.erb

<%= link_to "ホームに戻る", hello_index_path, class: 'btn btn-info' %>
<section class="wrapper-a">
    <div class="link-container">
    <div class="container-a">
        <div class="content-a">
            <h2 class="heading-a">Vaseの使い方</h2>
            <div class="list-a">
                <div class="list-item-a">コチラのページではVaseの使用方法について書いてあります。初めての方はこのページを参考にまずはアカウント作成をしてみましょう。</div>
                <br>
                <%= link_to "English page heare !", hello_link_en_path , :controller => "hello", :action => "link_en" ,class: 'btn btn-outline-danger' %>
            </div>
            
        </div>
    </div>
    </div>
</section>
<div class="how-menu-container">
<%= link_to "トップページ", hello_link_path , :controller => "hello", :action => "link" ,class: 'btn btn-outline-danger' %>
<%= link_to "新規登録方法", hello_log_path , :controller => "hello", :action => "log" ,class: 'btn btn-outline-danger' %>
<%= link_to "投稿を見る、する", hello_post_path , :controller => "hello", :action => "post" ,class: 'btn btn-outline-danger' %>
<%= link_to "マイページ", hello_my_path , :controller => "hello", :action => "my" ,class: 'btn btn-outline-danger' %>
</div>

<div class="box27">
    <span class="box-title">トップページ</span>
    Vaseはトップページでいくつかの機能をご利用いただけます。
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('about-vase.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            このページのことです。初めての方でも簡単に使用方法がわかるよう丁寧に説明しております。
            <br>
            Vaseは会員登録をしなくても利用できますが、登録をするとより一層このサービスを楽しめます。
            このページの説明をもとにさっそく会員登録をしてみましょう。
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('article 2.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            コチラのページでは定期的に更新されるお花に関する情報記事を読むことができます。
            <br>
            もし、自分の投稿作品のいいね数が多いと記事内で紹介される可能性が…！？
            未経験の方もこのサービスのいたるところにあるお花の情報で素敵なお花ライフを始めてみましょう✿
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('seasonal2.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            Vaseは作品投稿の際にお花の季節をタグ付けして投稿することができます。
            <br>
            このセクションにある季節アイコンをクリックすると、季節ごとの投稿作品を見ることができます。
            今の季節にはどんなお花があるのか、どんな飾り方がぴったりなのか見てみましょう。
            <%= image_tag('seasonal-show.jpg', :size => '200x100') %>
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('collection.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            ここではほかの人の作品一覧を見ることができます。
            <br>
            ※詳細を見るにはログインが必要です。
        </div>
    </div>
</div>



app/views/hello/link_en.html.erb
<%= link_to "back home", hello_index_path, class: 'btn btn-info' %>
<section class="wrapper-a">
    <div class="link-container">
    <div class="container-a">
        <div class="content-a">
            <h2 class="heading-a">How to use vase</h2>
            <div class="list-a">
                <div class="list-item-a">This page describes how to use the vase. If you are new to this site, please refer to this page and create an account first.</div>
                
            </div>
            
        </div>
    </div>
    </div>
</section>
<div class="how-menu-container">
<%= link_to "Top page", hello_link_en_path , :controller => "hello", :action => "link_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "New registration method", hello_log_en_path , :controller => "hello", :action => "log_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "View and do posts", hello_post_en_path , :controller => "hello", :action => "post_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "My page", hello_my_en_path , :controller => "hello", :action => "my_en" ,class: 'btn btn-outline-danger' %>
</div>

<div class="box27">
    <span class="box-title">Top page</span>
    Some functions of Vase are available on the top page.
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('about-vase.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        This page. We have carefully explained how to use it even if you are a beginner.
            <br>
            You can use Vase without registering as a member, but you can enjoy this service even more if you register.
            Let's register as a member based on the explanation on this page.
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('article 2.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        You can read information articles about flowers that are regularly updated on this page.
            <br>
            If there are a lot of likes for your work, it may be introduced in the article...! ?
            Let's start a wonderful flower life with flower information everywhere in this service even for inexperienced people ✿
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('seasonal2.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        Vase can tag and post the season of flowers when submitting a work.
            <br>
            Click on the Seasons icon in this section to see the submissions by season.
            Let's see what kind of flowers there are in this season and what kind of decoration is best.
            <%= image_tag('seasonal-show.jpg', :size => '200x100') %>
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('collection.jpg', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        Here you can see a list of other people's works.
            <br>
            *Login is required to see details.
        </div>
    </div>
</div>



app/views/hello/log.html.erb
<%= link_to "ホームに戻る", hello_index_path, class: 'btn btn-info' %>
<section class="wrapper-a">
    <div class="link-container">
    <div class="container-a">
        <div class="content-a">
            <h2 class="heading-a">Vaseの使い方</h2>
            <div class="list-a">
                <div class="list-item-a">コチラのページではVaseの使用方法について書いてあります。初めての方はこのページを参考にまずはアカウント作成をしてみましょう。</div>
                
            </div>
        </div>
    </div>
    </div>
</section>
<div class="how-menu-container">
<%= link_to "トップページ", hello_link_path , :controller => "hello", :action => "link" ,class: 'btn btn-outline-danger' %>
<%= link_to "新規登録方法", hello_log_path , :controller => "hello", :action => "log" ,class: 'btn btn-outline-danger' %>
<%= link_to "投稿を見る、する", hello_post_path , :controller => "hello", :action => "post" ,class: 'btn btn-outline-danger' %>
<%= link_to "マイページ", hello_my_path , :controller => "hello", :action => "my" ,class: 'btn btn-outline-danger' %>
</div>
<div class="box27">
    <span class="box-title">新規登録方法</span>
    会員登録の方法を説明します。
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('sign-up.PNG', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            トップページにある「新規登録はこちら」をクリックしてください。
            <br>
            ※新規登録を行った後は上のログインボタンからログインしてください。
            
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('sign-up-show.PNG', :size => '400x250') %>
        </div>
        <div class="how-script-box">
            「新規会員登録はこちら」をクリックすると、必要項目の入力フォームが表示されます。
            <br>
            登録したい名前（ほかのユーザーにも公開されます。）、メールアドレス、パスワード（ほかのユーザーには公開されません）を順番に入力し、「Signup」をクリックすれば完了です。
            
        </div>
    </div>
    
</div>

app/views/hello/log_en.html.erb
<%= link_to "back home", hello_index_path, class: 'btn btn-info' %>
<section class="wrapper-a">
    <div class="link-container">
    <div class="container-a">
        <div class="content-a">
            <h2 class="heading-a">How to use vase</h2>
            <div class="list-a">
                <div class="list-item-a">This page describes how to use the vase. If you are new to this site, please refer to this page and create an account first.</div>
                
            </div>
            
        </div>
    </div>
    </div>
</section>
<div class="how-menu-container">
<%= link_to "Top page", hello_link_en_path , :controller => "hello", :action => "link_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "New registration method", hello_log_en_path , :controller => "hello", :action => "log_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "View and do posts", hello_post_en_path , :controller => "hello", :action => "post_en" ,class: 'btn btn-outline-danger' %>
<%= link_to "My page", hello_my_en_path , :controller => "hello", :action => "my_en" ,class: 'btn btn-outline-danger' %>
</div>
<div class="box27">
    <span class="box-title">New registration method</span>
    I will explain how to register as a member.
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('sign-up.PNG', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        Please click "Register now" on the top page.
            <br>
            * Please log in using the login button above after making a new registration.
            
        </div>
    </div>
    <div class="how-to-container">
        <div class="how-img-box">
            <%= image_tag('sign-up-show.PNG', :size => '400x250') %>
        </div>
        <div class="how-script-box">
        Click "Register for new member" to display the input form for required items.
            <br>
            Enter the name you want to register (will be disclosed to other users), email address, password (will not be disclosed to other users) in order, and click “Sign up” to complete.
            
        </div>
    </div>
    
</div>

app/views/tweets/index.html.erb
<section class="home">
    <div class="home-container">
    
      <div class="text-focus-in">Vase</div>
      <div class="search-box">
        <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
          <div class="input-group">
          <%= text_field_tag :search, params[:search], placeholder: "キーワード検索", class: "form-control" %>
          <span class="input-group-btn">
              <%= button_tag "検索", :name => nil, class: "btn btn-info" %>
          </span>
          <%= form_tag tweets_path, method: :get, class: 'boards__searchForm' do %>
            <%= select_tag :tag_id,
                           options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                           {
                             prompt: 'タグで絞り込み検索',
                             onchange: 'submit(this.form);'
                           }
            %>
          <% end %>
          </div>
        <% end %>
      </div>
      <div class="menu-container">
          <div class="menu-button-box">
            <div class="about-box">
              <%= link_to "About more", hello_link_path , :controller => "hello", :action => "link" ,class: 'btn btn-outline-danger' %>
            
            </div>
            <div class="article-box">
              <%= link_to "Article", hello_show_path , :controller => "hello", :action => "show" ,class: 'btn btn-outline-danger' %>
          
            </div>
          
            <div class="new-post-box">
              <%= link_to "Post", new_tweet_path , :controller => "hello", :action => "show" ,class: 'btn btn-outline-danger' %>
            
              </div>
            <div class="mypage-box">
              <%= link_to "My page", user_path(current_user.id) , :controller => "hello", :action => "show" ,class: 'btn btn-outline-danger' %>
            
              </div>
              <div class="mypage-box">
              <%= link_to "Log out", destroy_user_session_path, method: :delete ,class: 'btn btn-outline-danger' %>
            
              </div>
          </div>
          <div class="season-menu-container">
            <div class="spring-box">
              <%= link_to image_tag('spring1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 1), method: :get %>
              <div class="spring-title">Spring</div>
            </div>
            <div class="summer-box">
              <%= link_to image_tag('summer1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 2), method: :get %>
              <div class="spring-title">Summer</div>
            </div>
            <div class="autumn-box">
              <%= link_to image_tag('autumn1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 3), method: :get  %>
              <div class="spring-title">Autumn</div>
            </div>
            <div class="winter-box">
              <%= link_to image_tag('winter1.jpg', :size => '120x100'), hello_spring_path(:tag_id => 4), method: :get  %>
              <div class="spring-title">Winter</div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

  


<div class="scroll-bg-content">
 
  <div class="scroll-bg bg-color04">
          
    <div id="page-box">
      
    </div>
      <hr class="cp_hr07" />
  
      <% @tweets.each do |t| %>
  
        <div class="tweet">
        
            <div class="tweet-user-name-box">
            <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
            </div>
            <div class="tweet-image-box">
              <% if t.image.present? %>
              <%= link_to tweet_path(t.id) do %>
                <%= image_tag t.image_url, size: '400x300'  %>
              <% end %>
              <% else %>
              <%= link_to tweet_path(t.id) do %>
                <img src="/images/default.jpg" width="400px" height="300px">
              <% end %>
              <% end %> 
              <figcaption>
              <div class="tweet-title-box">
              <% if t.title.present? %>
              <%= t.title %>
              <% t.tags.each do |tag| %>
                <%= tag.name %>
              <% end %>    
              <% else %>
              <a>タイトルなし</a>
              <% end %>
              </div>
              <div class="tweet-info-item">
              ✿<%= t.liked_users.count %>
              <%= link_to "詳細へ", tweet_path(t.id) ,class: 'btn btn-outline-danger'%>
              <% if t.user.id == current_user.id %>
              <%= link_to "編集", edit_tweet_path(t.id) , class: 'btn btn-outline-danger' %>
              <%= button_to "削除", tweet_path(t.id), method: :delete , class: 'btn btn-outline-danger' %>
              <% end %>
            </div>
            </figcaption>

              
              
            </div>
            
            
        </div>
       
      <% end %>
      
  </div>
</div>
<hr class="cp_hr07" />
<div id="page-box">

</div>



<%= javascript_pack_tag 'tweets/index' %>







app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>